package com.athuman.mynumber.web.util;

public class ConstValues {

	public static final String CHECKBOX_SELECT = "1";
	public static final String CHECKBOX_NOT_SELECT = "0";
	public static final String RADIO_SELECT = "01";
	public static final String MY_NUMBER_CONFIRM_01 = "01";
	public static final String MY_NUMBER_CONFIRM_02 = "02";
	public static final String MY_NUMBER_CONFIRM_03 = "03";
	public static final String MY_NUMBER_CONFIRM_VALUE_01 = "個人番号カード";
	public static final String MY_NUMBER_CONFIRM_VALUE_02 = "通知カード";
	public static final String MY_NUMBER_CONFIRM_VALUE_03 = "番号が記載された住民票のコピー";
	public static final String MY_NUMBER_CONFIRM_VALUE_04 = "番号が記載された住民票記載事項証明書";
	public static final String DRIVERS_LICENSE = "運転免許証";
	public static final String DRIVE_HISTORY_LICENSE = "運転経歴証明書";
	public static final String PASSPORT = "パスポート";
	public static final String BODY_DISABILITIES_NOTEBOOK = "身体障碍者手帳";
	public static final String MENTAL_DISABILITIES_NOTEBOOK = "精神障碍者保健福祉手帳";
	public static final String REABILITATION_NOTEBOOK = "療育手帳";
	public static final String STAY_CARD = "在留カード";
	public static final String CLEAR_PERSON = "本人であることが明らか";
	public static final String HEATH_INSURANCE_LICENSE = "健康保険被保険者証";
	public static final String PENSION_NOTBOOK = "年金手帳";
	public static final String OTHER = "その他";
	public static final String BLANK = "";
	public static final String DEPENDENTS_RELATIONSHIP_01 = "01";
	public static final String DEPENDENTS_RELATIONSHIP_02 = "02";
	public static final String DEPENDENTS_RELATIONSHIP_03 = "03";
	public static final String DEPENDENTS_RELATIONSHIP_04 = "04";
	public static final String DEPENDENTS_RELATIONSHIP_05 = "05";
	public static final String DEPENDENTS_RELATIONSHIP_06 = "06";
	public static final String DEPENDENTS_RELATIONSHIP_07 = "07";
	public static final String DEPENDENTS_RELATIONSHIP_VALUE_01 = "妻";
	public static final String DEPENDENTS_RELATIONSHIP_VALUE_02 = "夫";
	public static final String DEPENDENTS_RELATIONSHIP_VALUE_03 = "子供";
	public static final String DEPENDENTS_RELATIONSHIP_VALUE_04 = "父";
	public static final String DEPENDENTS_RELATIONSHIP_VALUE_05 = "母";
	public static final String DEPENDENTS_RELATIONSHIP_VALUE_06 = "兄弟・姉妹";
	public static final String DEPENDENTS_RELATIONSHIP_VALUE_07 = "その他";
	public static final String CONSENT_VALUE_0 = "0";
	public static final String CONSENT_VALUE_1 = "1";
	public static final String API_MSG_INVALID = "リクエストが不正です。";
	public static final String API_MSG_OK = "正常に処理は行われました。";
	public static final String API_MSG_NOITEM_RETURNED = "検索結果が0件です。";
	public static final String API_MSG_UNEXPECTED_ERROR = "予期せぬエラーが発生しました。";
	public static final String API_OTHER_ERROR = "複数件取得されました。";
	public static final int API_RETURNED_LIST_LENGTH_0 = 0;
	public static final int API_RETURNED_LIST_LENGTH_1 = 1;
	public static final int HIMODUKENO_LENGTH = 36;
	public static final int MYNUMBER_REGIST_MAX_CHECKBOX_CHECKED = 2;
	public static final String API_RESULT_0 = "0";
	public static final String API_RESULT_1 = "1";
	public static final String NO3INSURED = "0";
	public static final String SAVE_DB_OK = "1";
	public static final String SAVE_DB_FAIL = "0";
}
